package com.example.demotest.repository.one_to_one;

import com.example.demotest.entity.one_to_one.attribute.orphanRemoval.StudentDetailOneToOneAttributeOrphanRemoval2Entity;
import org.springframework.data.jpa.repository.JpaRepository;

public interface StudentDetailOneToOneAttributeOrphanRemoval2EntityRepository extends JpaRepository<StudentDetailOneToOneAttributeOrphanRemoval2Entity, Integer> {
}