package com.example.demotest.repository.one_to_one;

import com.example.demotest.entity.one_to_one.attribute.orphanRemoval.StudentDetailOneToOneAttributeOrphanRemoval1Entity;
import org.springframework.data.jpa.repository.JpaRepository;

public interface StudentDetailOneToOneAttributeOrphanRemoval1EntityRepository extends JpaRepository<StudentDetailOneToOneAttributeOrphanRemoval1Entity, Integer> {
}