package com.example.demotest.repository.one_to_many;

import com.example.demotest.entity.one_to_many.attribute.orphanRemoval.StudentBookOneToManyAttributeOrphanRemoval1Entity;
import org.springframework.data.jpa.repository.JpaRepository;

public interface StudentBookOneToManyAttributeOrphanRemoval1EntityRepository extends JpaRepository<StudentBookOneToManyAttributeOrphanRemoval1Entity, Integer> {
}