package com.example.demotest.repository.one_to_many;

import com.example.demotest.entity.one_to_many.attribute.orphanRemoval.StudentOneToManyAttributeOrphanRemoval2Entity;
import org.springframework.data.jpa.repository.JpaRepository;

public interface StudentOneToManyAttributeOrphanRemoval2EntityRepository extends JpaRepository<StudentOneToManyAttributeOrphanRemoval2Entity, Integer> {
}