package com.example.demotest.repository.one_to_many;

import com.example.demotest.entity.one_to_many.attribute.orphanRemoval.StudentOneToManyAttributeOrphanRemoval1Entity;
import org.springframework.data.jpa.repository.JpaRepository;

public interface StudentOneToManyAttributeOrphanRemoval1EntityRepository extends JpaRepository<StudentOneToManyAttributeOrphanRemoval1Entity, Integer> {
}